# Site settings
title: LaurieOnTech
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Laurie Barth's professional website featuring a technical blog and up to date speaking apparances.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laurieontech.com" # the base hostname & protocol for your site
twitter_username: laurieontech
github_username:  lstar19
keywords: Laurie Barth, Laurieontech, speaker, women in tech, developer, engineer

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
